language: rust
sudo: false

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: stable
        - rust: beta

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev

cache:
    apt: true
    directories:
        - target/debug/deps

script:
    - ./all_unit_tests.sh && ./integration_tests.sh

after_success: |
    [ $TRAVIS_RUST_VERSION = nightly ] &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov --exclude-pattern=/.cargo target/kcov target/debug/emcache-*
    ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/emcache-* --ignored

notifications:
    email: true
